spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stocksense
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  threads:
    virtual:
      enabled: true

server:
  port: 8081

alphavantage:
  api:
    key: HXW27CL9C8V78EXL

jwt:
  secret: "your-256-bit-secret-here-change-in-production-min-32-chars"
  expiration: 604800000   # 7 days in ms

google:
  client-id: "724652717839-u1lacrp7rmj5rp2117vhnpoj26t5vgm5.apps.googleusercontent.com"

logging:
  level:
    com.stocksense: DEBUG
    com.stocksense.service.StockService: INFO